name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8  
  - numpy
  - matplotlib
  - scikit-learn
  - biopython
  - snakemake
  - pip
  - pip:
      - snakemake
      - TMscore  
